# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#dde4e4"

# Title color for boxes
theme[title]="#dde4e4"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#80d4d9"

# Background color of selected item in processes box
theme[selected_bg]="#252b2b"

# Foreground color of selected item in processes box
theme[selected_fg]="#dde4e4"

# Color of inactive/disabled text
theme[inactive_fg]="#bec8c9"

# Graph text color
theme[graph_text]="#bec8c9"

# Meter background color
theme[meter_bg]="#161d1d"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#bec8c9"

# Cpu box outline color
theme[cpu_box]="#3f4949"

# Memory/disks box outline color
theme[mem_box]="#3f4949"

# Net up/down box outline color
theme[net_box]="#3f4949"

# Processes box outline color
theme[proc_box]="#3f4949"

# Box divider line and small boxes line color
theme[div_line]="#3f4949"

# Temperature graph colors
theme[temp_start]="#b5c7e9"
theme[temp_mid]="#b1cccd"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#b5c7e9"
theme[cpu_mid]="#b1cccd"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#b5c7e9"
theme[free_mid]="#b5c7e9"
theme[free_end]="#b5c7e9"

# Mem/Disk cached meter
theme[cached_start]="#80d4d9"
theme[cached_mid]="#80d4d9"
theme[cached_end]="#80d4d9"

# Mem/Disk available meter
theme[available_start]="#b1cccd"
theme[available_mid]="#b1cccd"
theme[available_end]="#b1cccd"

# Mem/Disk used meter
theme[used_start]="#b5c7e9"
theme[used_mid]="#b1cccd"
theme[used_end]="#ffb4ab"

# Download graph colors
theme[download_start]="#b5c7e9"
theme[download_mid]="#b5c7e9"
theme[download_end]="#b5c7e9"

# Upload graph colors
theme[upload_start]="#b1cccd"
theme[upload_mid]="#b1cccd"
theme[upload_end]="#b1cccd"

# Process graph colors
theme[process_start]="#80d4d9"
theme[process_mid]="#80d4d9"
theme[process_end]="#80d4d9"
